# -*- coding: utf-8 -*-
"""Apple Dashboard (Assignment 3) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdrdpI-VUDqDK41LY62X_ECSf0V3Y4Nl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('apple_stock_data.csv')
df

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

# Ensure 'Date' column is in datetime format and sort the DataFrame
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(by='Date')

# --- KPI Calculations ---
latest_close = df['AAPL.Close'].iloc[-1]
previous_close = df['AAPL.Close'].iloc[-2] if len(df) > 1 else latest_close # Handle case of single data point
daily_change_percent = ((latest_close - previous_close) / previous_close) * 100 if previous_close != 0 else 0

# Calculate 52-week high and low
one_year_ago = df['Date'].iloc[-1] - pd.DateOffset(years=1)
df_last_year = df[df['Date'] >= one_year_ago]
fifty_two_week_high = df_last_year['AAPL.High'].max() if not df_last_year.empty else np.nan
fifty_two_week_low = df_last_year['AAPL.Low'].min() if not df_last_year.empty else np.nan

avg_daily_volume = df['AAPL.Volume'].mean()

# --- Dashboard Layout ---
# Create subplots for the dashboard layout:
# Row 1 & 2: KPI Cards (2 per row)
# Row 3: Line Chart, Bar Chart
# Row 4: Heatmap, Pie Chart
fig = make_subplots(
    rows=4, cols=2,
    specs=[
        [{"type": "indicator"}, {"type": "indicator"}],       # Row 1: KPI 1, KPI 2
        [{"type": "indicator"}, {"type": "indicator"}],       # Row 2: KPI 3, KPI 4
        [{"type": "xy"}, {"type": "xy"}],                     # Row 3: Line Chart, Bar Chart
        [{"type": "heatmap"}, {"type": "domain"}]             # Row 4: Heatmap, Pie Chart
    ],
    row_heights=[0.1, 0.1, 0.4, 0.4], # Adjust heights for better visual balance
    vertical_spacing=0.08,
    horizontal_spacing=0.08,
    subplot_titles=(
        "", "",
        "", "",
        "Stock Price Over Time", "Daily Trading Volume",
        "Feature Correlation", "Daily Return Categories"
    )
)

# --- Add KPI Cards ---
fig.add_trace(
    go.Indicator(
        mode="number+delta",
        value=latest_close,
        title={"text": "Latest Close"},
        delta={'reference': previous_close, 'relative': True, 'position': "bottom"},
        number={'valueformat': ".2f"}
    ), row=1, col=1
)
fig.add_trace(
    go.Indicator(
        mode="number+delta",
        value=daily_change_percent,
        number={'suffix': "%", 'valueformat': ".2f"},
        title={"text": "Daily Change %"},
        delta={'reference': 0, 'relative': False, 'position': "bottom"}
    ), row=1, col=2
)
fig.add_trace(
    go.Indicator(
        mode="number",
        value=fifty_two_week_high,
        title={"text": "52-Week High"},
        number={'valueformat': ".2f"}
    ), row=2, col=1
)
fig.add_trace(
    go.Indicator(
        mode="number",
        value=fifty_two_week_low,
        title={"text": "52-Week Low"},
        number={'valueformat': ".2f"}
    ), row=2, col=2
)

# --- Add Line Chart (Stock Price) ---
fig.add_trace(
    go.Scatter(x=df['Date'], y=df['AAPL.Close'], mode='lines', name='AAPL.Close',
               line=dict(color='blue'), showlegend=False),
    row=3, col=1
)
fig.update_xaxes(title_text="Date", row=3, col=1)
fig.update_yaxes(title_text="Closing Price", row=3, col=1)

# --- Add Bar Chart (Daily Volume) ---
fig.add_trace(
    go.Bar(x=df['Date'], y=df['AAPL.Volume'], name='AAPL.Volume',
           marker_color='lightseagreen', showlegend=False),
    row=3, col=2
)
fig.update_xaxes(title_text="Date", row=3, col=2)
fig.update_yaxes(title_text="Volume", row=3, col=2)

# --- Add Heatmap (Correlation Matrix) ---
numeric_df = df.select_dtypes(include=[np.number]).drop(columns=['Unnamed: 0'], errors='ignore')
corr_matrix = numeric_df.corr()

fig.add_trace(
    go.Heatmap(
        z=corr_matrix.values,
        x=corr_matrix.columns,
        y=corr_matrix.columns,
        colorscale='Viridis',
        colorbar_title="Correlation"
    ),
    row=4, col=1
)
fig.update_xaxes(showgrid=False, row=4, col=1)
fig.update_yaxes(showgrid=False, row=4, col=1)

# --- Add Pie Chart (Daily Return Distribution) ---
df['Daily_Return'] = df['AAPL.Close'].pct_change() * 100
# Categorize daily returns
df['Return_Category'] = pd.cut(df['Daily_Return'],
                               bins=[-np.inf, -0.5, 0.5, np.inf],
                               labels=['Negative (< -0.5%)', 'Neutral (-0.5% to 0.5%)', 'Positive (> 0.5%)'],
                               include_lowest=True)
return_counts = df['Return_Category'].value_counts().sort_index()

fig.add_trace(
    go.Pie(
        labels=return_counts.index,
        values=return_counts.values,
        name="Daily Returns",
        marker_colors=['red', 'gray', 'green'],
        hole=0.3,
        showlegend=True
    ),
    row=4, col=2
)

# --- Update Overall Layout ---
fig.update_layout(
    height=1200,
    showlegend=False,
    template="plotly_white", # Professional look
    hovermode="x unified",
    margin=dict(t=100, b=50, l=50, r=50), # Adjust margins
    title_text="<b>Apple Stock Dashboard</b>", # Add the main title here
    title_x=0.5 # Center the title
)

# --- Add Date Range Filter to Line Chart ---
fig.update_xaxes(
    rangeslider_visible=True,
    rangeselector=dict(
        buttons=list([
            dict(count=1, label="1m", step="month", stepmode="backward"),
            dict(count=6, label="6m", step="month", stepmode="backward"),
            dict(count=1, label="YTD", step="year", stepmode="todate"),
            dict(count=1, label="1y", step="year", stepmode="backward"),
            dict(step="all")
        ])
    ),
    row=3, col=1 # Apply to the line chart
)

fig.show()
